# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

licenses:
  - 'android-sdk-license-.+'
  - 'android-sdk-preview-license-.+'
  - 'google-gdk-license-.+'

script: ./gradlew build
